###    Le variabili volumes sono mappate come - host_folder:container_folder
###    Correggere all'occorrenza i path per le cartelle sull'host ma lasciare inalterati i path sui container docker  


client:

  image: docker-registry.services.iit.cnr.it/smartclockclient:latest

  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  - /home/epas/client:/client/data

  environment:

  - BR_IP_ADDRESS=192.168.100.101
  - BR_USER=FC03
  - BR_PASSWORD=258456
  - SERVER_HOST=epas.amministrazione.cnr.it
  - SERVER_PROTOCOL=https
  - SERVER_PORT=443
  - EPAS_CLIENT_USER=perugiaBadge
  - EPAS_CLIENT_PASSWORD=perugiaBadge
  - LOG_LEVEL=DEBUG
#  - CRON=* * * * *

  restart: always

client2:

  image: docker-registry.services.iit.cnr.it/smartclockclient:latest

  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
  - /home/epas/client-rende:/client/data

  environment:

  - BR_IP_ADDRESS=194.119.196.94
  - BR_USER=FC03
  - BR_PASSWORD=12345
  - SERVER_HOST=epas.amministrazione.cnr.it
  - SERVER_PROTOCOL=https
  - SERVER_PORT=443
  - EPAS_CLIENT_USER=rendeIrpiBadge
  - EPAS_CLIENT_PASSWORD=rendeIrpiBadge
  - LOG_LEVEL=DEBUG
#  - CRON=* * * * *

  restart: always

