###    Le variabili volumes sono mappate come - host_folder:container_folder
###    Correggere all'occorrenza i path per le cartelle sull'host ma lasciare inalterati i path sui container docker  

postgres:
  image: postgres:9.4

  volumes:
    - /opt/epas/db/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /opt/epas/backups/:/tmp:ro

  restart: always

nginx:

  image: jwilder/nginx-proxy:latest

  ports:
    - "80:80"
#    - "443:443"

  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /var/run/docker.sock:/tmp/docker.sock
#    - /opt/epas/certs/:/etc/nginx/certs

  restart: always

epas:

  image: docker-registry.services.iit.cnr.it/epas:latest

  volumes:
    - /opt/epas/logs:/home/epas/epas/logs
    - /opt/epas/attachments:/home/epas/epas/data/attachments
    - /opt/epas/backups:/home/epas/epas/backups
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

  environment:
#### APPLICAZIONE ####
    - VIRTUAL_HOST=
#    - PROTOCOL=                             # default: http  -- (http,https)
#    - EPAS_SHIB_LOGIN=                      # default: false  -- (true,false)
#    - JOBS_ACTIVE=                          # default: false  -- (true,false) --  Se forzato a true abilita l'esecuzione di tutti i job
#    - LOG_LEVEL=                            # default: INFO   -- (OFF,FATAL,ERROR,WARN,INFO,DEBUG,TRACE,ALL)
#    - LOG_ON_FILE=                          # default: false  -- (true, false)
#    - SKIP_IP_CHECK=                        # default: false -- (true,false) -- Disabilita il controllo sugli indirizzi ip delle richieste
#    - URL_ATTESTATI=                        # default: https://attestativ2.rm.cnr.it
#    - URL_USER=
#    - URL_PASS=
#### Container ####
#    - BACKUP_CRON=                          # default: disattivato. (utilizzare il format del crontab. Es. 0 0 * * *)
#    - CERT_NAME=                            # default: valore specificato in VIRTUAL_HOST -- Specifica un nome diverso per i file del certificato SSL
    - TZ=Europe/Rome                        # Imposta la timezone nel container docker
#### Connessione DB ####
#    - DB_HOST=                              # default: indirizzo assegnato al container postgres linkato
#    - DB_NAME=                              # default: epas
#    - DB_PASS=                              # default: "non necessaria"
#    - DB_PORT=                              # default: 5432
#    - DB_USER=                              # default: postgres
#### server SMTP ####
#    - SMTP_HOST=                            # default: smtp.cnr.it
#    - SMTP_PORT=                            # default: 25 se SMTP_CHANNEL è impostato clear o starttls; 465 se impostato su ssl
#    - SMTP_CHANNEL=                         # default: clear -- (clear, ssl ,starttls)
#    - SMTP_FROM=                            # default: epas@cnr.it -- Indirizzo utilizzato per il campo mittente delle mail inviate dal sistema
#    - SMTP_PROTOCOL=                        # default: smtp -- (smtp, smtps)
#    - SMTP_USER=                            # user utilizzato per l'autenticazione sul server smtp (se necessario)
#    - SMTP_PASS=                            # password utilizzato per l'autenticazione sul server smtp (se necessaria)
#### Interfacce Rest ####
#    - PERSEO_BASE=                          # default: http://perseo.devel.iit.cnr.it
#    - PERSEO_PASS=                          # password utilizzata per l'autenticazione con le interfacce rest di perseo
#    - PERSEO_USER=                          # user utilizzato per l'autenticazione con le interfacce rest di perseo
#### Integrazione OIL ###
#    - OIL_ENABLED=true                      # default: false. Se impostato abilita l'invio delle segnalazioni ad OIL
#    - OIL_CATEGORIES                        # default: 4:epas. Specifica le categorie utilizzate in OIL.
#                                                       La lista delle categorie è suddivisa da ",", il campo ":" è utilizzato invece
#                                                       come separatore tra l'id della categoria ed il nome visualizzato all'utente, 
#                                                       es.: 1:Registrazione Timbrature,2:Gestione Assenze,3:Gestione Competenze,4:Altro
#    - OIL_CATEGORIES_SELECTED               # default: 4. Questo default è dato dall'ambiente di test di OIL. 
#                                                       Contiene l'id della categoria da mostrare già selezionata all'utente finale. 

  links:
    - postgres

  restart: unless-stopped
