Configuration(defaultConfiguration):
    inUse: true
    initUseProgram: 2012-07-30
    beginDate: 2010-01-01
    endDate: 2099-12-31
    instituteName: IIT
    emailToContact:
    seatCode: 223400
    urlToPresence:
    userToPresence:
    passwordToPresence:
    monthOfPatron: 6
    dayOfPatron: 17
    numberOfViewingCoupleColumn: 3 
    isMealTimeShorterThanMinimum: false
    isIntervalTimeCutFromWorkingTime: false
    calculateIntervalTimeWithoutReturnFromIntevalTime: false
    mealTicketAssignedWithMealTimeReal: false
    mealTicketAssignedWithReasonMealTime: false
    insertAndModifyWorkingTimeWithPlusToReduceAtRealWorkingTime: false
    addWorkingTimeInExcess: false
    isLastDayBeforeXmasEntire: false
    isLastDayBeforeEasterEntire: false
    isLastDayOfTheYearEntire: false
    isFirstOrLastMissionDayAHoliday: false
    isHolidayInMissionAWorkingDay: false
    workingTime: 432
    workingTimeToHaveMealTicket: 360
    mealTime: 30
    monthExpiryVacationPastYear: 8
    dayExpiryVacationPastYear: 31
    minimumRemainingTimeToHaveRecoveryDay: 432
    monthExpireRecoveryDaysOneThree: 0
    monthExpireRecoveryDaysFourNine: 4
    maxRecoveryDaysOneThree: 22
    maxRecoveryDaysFourNine: 0
    residual: atMonth
    maximumOvertimeHours: 0
    holydaysAndVacationsOverPermitted: false
    hourMaxToCalculateWorkTime: 5
    canPeopleAutoDeclareWorkingTime: false
    canPeopleAutoDeclareAbsences: false
    capacityOneThree: onEndOfMonthResidual
    capacityFourEight: onEndOfMonthResidual
    canInsertMoreAbsenceCodeInDay: false
    ignoreWorkingTimeWithAbsenceCode: false
    canPeopleUseWebStamping: false
    textForMonthlySituation:
